export const restaurants = [
  {
    id: "78511",
    name: "NIC Ice Creams",
    cloudinaryImageId: "c8b98c4064dc2fd6bdf350212e5f0bd5",
    locality: "8th Block",
    areaName: "Koramangala",
    costForTwo: "₹120 for two",
    cuisines: ["Ice Cream", "Desserts"],
    avgRating: 4.6,
    veg: true,
  },
  {
    id: "312",
    name: "Beijing Bites",
    cloudinaryImageId: "sllx2xvfstuhyn35uirf",
    locality: "5th A Block",
    areaName: "Koramangala",
    costForTwo: "₹450 for two",
    cuisines: ["Chinese", "Thai", "Pan-Asian"],
    avgRating: 4.4,
  },
  {
    id: "59627",
    name: "La Pino'z Pizza",
    cloudinaryImageId: "ntjshqsv2k7vxtv7vmib",
    locality: "Koramangala",
    areaName: "Koramangala",
    costForTwo: "₹251 for two",
    cuisines: ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"],
    avgRating: 4.1,
  },
  {
    id: "535102",
    name: "Nomad Pizza- Traveller Series",
    cloudinaryImageId: "a14f952df15d37ac5017519beab18683",
    locality: "Roopena Agrahara",
    areaName: "HSR",
    costForTwo: "₹850 for two",
    cuisines: ["Pizzas", "Italian", "Beverages"],
    avgRating: 4.2,
  },
  {
    id: "562239",
    name: "Sri Udupi Food Hub",
    cloudinaryImageId: "knntc6flk5amjmwqfzt2",
    locality: "Bhuvanappa Layout",
    areaName: "S G Palya",
    costForTwo: "₹200 for two",
    cuisines: [
      "South Indian",
      "North Indian",
      "Chinese",
      "Indian",
      "Ice Cream",
      "Chaat",
      "Beverages",
      "Desserts",
    ],
    avgRating: 4.3,
  },
  {
    id: "19563",
    name: "The Bowl Company",
    cloudinaryImageId: "bb6049fae59b8a2413a9177eb0338b49",
    locality: "Jakkasandra",
    areaName: "Koramangala",
    costForTwo: "₹300 for two",
    cuisines: [
      "Pan-Asian",
      "Continental",
      "North Indian",
      "Desserts",
      "American",
      "Asian",
      "Beverages",
      "Biryani",
      "Chinese",
      "European",
      "Grill",
      "Hyderabadi",
      "Indian",
      "Italian",
      "Kebabs",
      "Lucknowi",
      "Mediterranean",
      "Mexican",
      "Mughlai",
      "Oriental",
      "Pastas",
      "Punjabi",
      "Raja",
    ],
    avgRating: 4.4,
  },
  {
    id: "381854",
    name: "ITC Sunfeast Baked Creations",
    cloudinaryImageId: "c457c9dcef7c8ada74ecc6032ea3699c",
    locality: "Koramangala",
    areaName: "Koramangala",
    costForTwo: "₹600 for two",
    cuisines: ["Bakery", "Desserts", "Continental", "Cafe", "Snacks"],
    avgRating: 4.5,
  },
  {
    id: "307050",
    name: "Call Me Chow",
    cloudinaryImageId: "soegobqsiqvhmkfvnnkj",
    locality: "8th Block",
    areaName: "Koramangala",
    costForTwo: "₹400 for two",
    cuisines: ["Chinese", "Pan-Asian"],
    avgRating: 4.3,
  },
  {
    id: "38634",
    name: "Third Wave Coffee",
    cloudinaryImageId: "d96267738c19ec62acb5390e52faba41",
    locality: "Koramangala",
    areaName: "Koramangala",
    costForTwo: "₹400 for two",
    cuisines: ["Beverages", "Bakery", "Continental"],
    avgRating: 4.4,
  },
];
